# Generated by Django 6.0 on 2025-12-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_booking_location_booking_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
