# Generated by Django 6.0 on 2025-12-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_booking_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
