# Generated by Django 6.0 on 2025-12-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_booking_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerental',
            name='service_type',
            field=models.CharField(choices=[('RENTAL', 'Services Rental'), ('SERVICE', 'Services Maintenance')], max_length=10),
        ),
    ]
