# Generated by Django 6.0 on 2025-12-19 01:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_booking_status_order_orderitem_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
    ]
