# Generated by Django 6.0 on 2025-12-19 01:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
