# Generated by Django 6.0 on 2025-12-19 07:29

import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, help_text='Formatted address from Google Maps', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, help_text='GPS Coordinates (Lat, Lng)', max_length=63, null=True),
        ),
    ]
