# Generated by Django 6.0 on 2025-12-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_order_city_order_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='location',
        ),
    ]
