# Generated by Django 6.0 on 2025-12-23 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerental',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+855...'.", regex='^\\+?855?\\d{9,10}$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+855...'.", regex='^\\+?855?\\d{9,10}$')]),
        ),
        migrations.AlterField(
            model_name='servicerental',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerental',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicerental',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
