# Generated by Django 6.0 on 2025-12-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_alter_servicerental_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerental',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
