# Generated by Django 6.0 on 2025-12-23 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_alter_servicerental_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.servicerental', verbose_name='Services'),
        ),
        migrations.AlterField(
            model_name='servicerental',
            name='service_type',
            field=models.CharField(choices=[('RENTAL', 'Rental'), ('SERVICE', 'Maintenance')], max_length=10),
        ),
    ]
